USE sovisy
CREATE TABLE SALESINFO(
ID INT IDENTITY(1,1) PRIMARY KEY ,
ITEM_CODE VARCHAR(15),     --ITEM_CODE VARCHAR(15) UNIQUE-,
ITEM_NAME VARCHAR(30),     --ITEM_CODE VARCHAR(15) NOT NULL-,
ITEM_GRADE VARCHAR(1),
ITEM_ORIGIN VARCHAR(15),
ITEM_PRICE MONEY

)
--ERROR COMMAND
--INSERT INTO SALESINFO VALUES
--('ABC1345','NUT8"', '8', 'PUNJAB', 8.00, 'INDIA', 9)

--TO SHOW TABLE-
SELECT * FROM SALESINFO

--TO DELETE OBJECT(ENTIRE TABLE WITH DATA)-
DROP TABLE SALESINFO

--TO INSERT DATA-
INSERT INTO SALESINFO VALUES
('ABC1235','NUT8"', '8', 'PUNJAB',      8.00, 'INDIA', '+91'),
('ABC4567','NUT6"', '6', 'PUNJAB',      7.50, 'INDIA', '+91'),
('ABC5678','NUT4"', '6', 'MAHARASHTRA', 5.50, 'INDIA', '+91'),
('ABC7890','NUT2"', '8', 'GUJARAT',     4.00, 'INDIA', '+91')
 
 --UNIQUE ID-
 ALTER TABLE SALESINFO
 ADD CONSTRAINT U_ID UNIQUE(ITEM_CODE)

--TO DELETE CONSTRAINTS-
ALTER TABLE SALESINFO
DROP CONSTRAINT C_CODE

--TO DELETE DATA-
TRUNCATE TABLE SALESINFO

--TO ADD OBJECT(NEW COLUMN)-
ALTER TABLE SALESINFO
ADD COUNTRY VARCHAR(10)

--TO MAKE CHOICE(LIKE, MALE OR FEMALE)
ALTER TABLE SALESINFO
ADD CONSTRAINT LIM_COUNTRY CHECK (COUNTRY IN ('INDIA', 'AUSTRALIA'))

--TO DELETE PERTICULAR ROW 
DELETE FROM SALESINFO
WHERE ID=4

--TO ADD PERTICULAR COLUMN
ALTER TABLE SALESINFO
ADD PRICERANGE BIGINT

--TO DELETE PERTICULAR COLUMN
ALTER TABLE SALESINFO
DROP COLUMN PRICERANGE

--TO DELETE ALL THE DATABASE
DROP DATABASE sovisy

--TO SET RANGE BETWEEN THIS AND THIS
ALTER TABLE SALESINFO
ADD CONSTRAINT P_RANGE CHECK (PRICERANGE BETWEEN 5 AND 10)

--TO CHANGE DATAYPE VALUES
ALTER TABLE SALESINFO 
ALTER COLUMN COUNTRY_CODE VARCHAR(3)

--ERROR COMMAND
ALTER TABLE SALESINFO
ADD CONSTRAINT C_CODE CHECK (COUNTRY_CODE LIKE '[+][0-9][0-9]')

ALTER TABLE SALESINFO
DROP CONSTRAINT C_CODE

--TO SET PHONE NUMBER
ALTER TABLE SALESINFO
ADD PHONE INT
CONSTRAINT CHK_PHONE CHECK (PHONE like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')

INSERT INTO SALESINFO VALUES
('ABC1235','NUT8"', 'PUNJAB', 8.00, 'INDIA', '+91', 1111111111)

--TO DELETE PERTICULAR COLUMN
ALTER TABLE SALESINFO
DROP COLUMN COUNTRY_CODE

--TO ADD PERTICULAR COLUMN
ALTER TABLE SALESINFO
ADD COUNTRY_CODE INT

INSERT INTO SALESINFO VALUES
('ABC1236','NUT8"', 'PUNJAB', 8.00, 'INDIA', 1111111111 , '+91')