DROP TABLE EMPLOYEES

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID	VARCHAR(20) PRIMARY KEY,
FIRST_NAME VARCHAR(25),
LAST_NAME VARCHAR(25),
EMAIL VARCHAR(25),
PHONE_NUMBER BIGINT,
HIRE_DATE DATE,
JOB_ID VARCHAR(20) CONSTRAINT FK_JOB_ID_KEY FOREIGN KEY REFERENCES DBO.JOB(JOB_ID),
SALARY BIGINT,
COMMISSION DECIMAL(2,2),
MANAGER_ID VARCHAR(20),
DEPARTMENT_ID VARCHAR(20) CONSTRAINT FK_DEP_ID_KEY FOREIGN KEY REFERENCES DBO.DEPARTMENTS(DEPARTMENT_ID)
)

CREATE TABLE INVENTORY(
PID VARCHAR(10) NOT NULL, 
QUANTITY INTEGER,
LOCATION VARCHAR(128),
PRIMARY KEY (PID) 
)

CREATE TABLE SALES(
SALESMAN_ID VARCHAR(10) PRIMARY KEY,
SALESMAN_NAME VARCHAR(25),
SALESMAN_CITY VARCHAR(15),
SALESMAN_COMMISION BIGINT,
TOTAL_SALES BIGINT
)

CREATE TABLE CAR_SALES(
CS_ID VARCHAR(10) NOT NULL PRIMARY KEY,
EMPLOYEE_ID VARCHAR(20) CONSTRAINT EMPLOYEE_FK FOREIGN KEY REFERENCES DBO.EMPLOYEES(EMPLOYEE_ID),
PID VARCHAR(10) CONSTRAINT PID_FK FOREIGN KEY REFERENCES DBO.INVENTORY(PID),
SALESMAN_ID VARCHAR(10) CONSTRAINT SALESMAN_FK FOREIGN KEY REFERENCES DBO.SALES(SALESMAN_ID)
)
SELECT * FROM CAR_SALES